### ISSUE TITLE
Retrieving schema attempts

### ISSUE THREAD

**Issue by DimaBalyasnicov** [kazei92/pyobiee#3]
Hi.
First of all,  thank you, this library was really helpful in automating my reports. I'm not really familiar with backends and such, so it was really easy-to-use. 
It works just fine with 11c Oracle BI, I don't have any bugs to report. I was just wondering if I can do something to make it do less attempts to find schema. 
Now it can take from 2 to 25 attempts to find schema, never on first try. It was able to find it in the end, but I imagine it might be not able to find schema within 30 attempts sometimes, I haven't tested it thoroughly. By looking at the code it seems like the function does the same thing over and over again. So if the code is the same I wonder if I can do something about it. I'm passing an sql query, so that I can modify the data without extra work with settings in obi reports. Do attempts depend on how complex is the query? Is there something I can tweak? I guess I can just while loop until I get data, but this solution doesn't really speak to me.

**Comment by tikacanon** [comment]
Hi Dima,

In the latest version available on PyPi 0.20, I have optimised the schema extraction.
However, from experience, the reporting server needs time to generate schema.
Depending on the report complexity, it can take some time. That's why it repeats the request until the schema is ready. The intervals of thess requests are customisable, but you would need to modify them in the source code: 

https://github.com/kazei92/pyobiee/blob/master/pyobiee/functions.py
line 22

**Comment by kazei92** [comment]
closed
